name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
            image: ubuntu:focal 
    
    steps:
      - name: Set up environment
        run : |
          apt update
          apt add gcc libc-dev golang-1.17
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: codecov/codecov-action@v2
        with:
          dry_run: true
          verbose: true
    
      - name: Format
        run: |
          res="$(gofmt -s -l .)"
          if [ "$(echo "$res" | tr -d '\n' | wc -l)" -gt 0 ]; then
          echo "Unformatted source code:"
          echo "$res"
          exit 1
          fi
 
      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./...      

      - name: Build
        run: |
          go build .
