name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16.10-alpine3.14
    
    steps:
      - name: Set up environment
        run : |
          apk update
          apk add gcc libc-dev bash perl curl
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Formatting
        run: |
          go install golang.org/x/tools/cmd/goimports@latest      
          res="$(goimports -l .)"
          if [ "$(echo "$res" | tr -d '\n' | wc -l)" -gt 0 ]; then
          echo "$res"
          exit 1
          fi
 
      - name: Vet
        run: |
          go vet ./...

      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.2"
          install-go: false

      - name: Test
        run: |
          go test ./...

      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          
      - name: Build
        run: |
          go build .
