name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16.10-alpine3.14
    
    steps:
      - name: Set up environment
        run : |
          apk update
          apk add gcc libc-dev bash perl curl make
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest      
          res="$(goimports -l .)"
          if [[ "$(printf '%s' "$res")" != '' ]]; then
            echo "Unformatted source code:"
            echo "$res"
            exit 1
          fi
 
      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./...

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2021.1.2"
          install-go: false

      - name: Build
        run: |
          make
